//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEmlakApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanDetay
    {
        public int IlanDetayID { get; set; }
        public int IlanId { get; set; }
        public int BinaYasi { get; set; }
        public int BulunduguKat { get; set; }
        public bool Durum { get; set; }
        public int EmlakTipiId { get; set; }
        public int EmlakSahibiId { get; set; }
        public string Esyali { get; set; }
        public int Fiyat { get; set; }
        public int KatSayisi { get; set; }
        public int MetreKare { get; set; }
        public int OdaSayisi { get; set; }
        public int GoruntulenmeSayisi { get; set; }
        public int BegenmeSayisi { get; set; }
        public int YorumSayisi { get; set; }
        public string KoordinatX { get; set; }
        public string KoordinatY { get; set; }
        public int AdresId { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual EmlakTipi EmlakTipi { get; set; }
        public virtual Ilanlar Ilanlar { get; set; }
        public virtual Kisiler Kisiler { get; set; }
        public virtual Kisiler Kisiler1 { get; set; }
    }
}
