//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEmlakApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiRol
    {
        public int KisiRolID { get; set; }
        public int RolID { get; set; }
        public int KisiID { get; set; }
    
        public virtual Kisiler Kisiler { get; set; }
        public virtual Roller Roller { get; set; }
    }
}
